### ISSUE TITLE
Calculating BPM from sp.speed

### ISSUE THREAD

**Issue by kieranmaraj** [rconstanzo/SP-tools#2]
Hey Rodrigo! Apologies if this isn't the best place to ask this, but I was wondering if there's a way to use the information reported by sp.speed and convert it into a BPM value?

**Comment by rconstanzo** [comment]
Kind of, as it starts off as that, but I run it through some log scaling to convert it to 0. to 1. range, so it's probably easiest to just do the calculation directly. It's a pretty "dumb" algorithm I'm using. Essentially this:
![Screenshot 2023-02-02 at 11 05 00 pm](https://user-images.githubusercontent.com/2747015/216471183-bcb51535-8bc0-418c-aa3a-73454612bdc7.png)

(the `p cputimer` thing is from the helpfile of `cpuclock`

**Comment by kieranmaraj** [comment]
fantastic, thanks so much!
