### ISSUE TITLE
fluid.voiceallocator missing

### ISSUE THREAD

**Issue by jaaaamIron** [rconstanzo/SP-tools#3]
Hi. I'm trying to run your 'Input triggering ambient accompaniment' example, but fluid.voiceallocator is missing. I have Flucoma 1.0.6 via package manager. Do you know where this is meant to live? Thanks!

**Comment by rconstanzo** [comment]
Ah good shout. I accidentally built that into a release patch, but it's still not a released object.

Here's a replacement patch that you can drop into the examples folder (I'll update the main link).
[Input triggering ambient accompaniment.maxpat.zip](https://github.com/rconstanzo/SP-tools/files/14073857/Input.triggering.ambient.accompaniment.maxpat.zip)
